I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 349, in script
    show screen ligthen
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen ligthen is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 349, in script
    show screen ligthen
  File "D:\Local Folder\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1968, in execute
    self.call("execute")
  File "D:\Local Folder\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1950, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\Local Folder\Downloads\renpy-8.2.1-sdk\renpy\statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "D:\Local Folder\Downloads\renpy-8.2.1-sdk\renpy\display\screen.py", line 1322, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen ligthen is not known.


Windows-10-10.0.26100 AMD64
Ren'Py 8.2.1.24030407
Shadows Defy the Night 1.0
Sun Apr 14 11:19:45 2024
